server:
  port: 8089

spring:
  application:
    name: gateway-config
  cloud:
    nacos:
      discovery:
        server-addr: nacos.sunnly.wang:8848
    sentinel:
      transport:
        port: 8721
        dashboard: localhost:8080
    gateway:
#      设置服务名路由策略
      discovery:
        locator:
          enabled: true
      default-filters:
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      routes:
        - id: ADMIN-CONSUMER
          # 采用 LoadBalanceClient 方式请求，以 lb:// 开头，后面的是注册在 Nacos 上的服务名
          uri: lb://admin-consumer
          order: 8999
          predicates:
            - Path=/user/**
#            - Method=GET,POST

# 配置日志级别，方别调试
logging:
  level:
    org.springframework.cloud.gateway: debug

