sunnly:
    security:
      auth:
#       鉴权服务器ID（用了查找鉴权服务器）
        service-id: sunnly-oauth
#       服务鉴权
        client:
          id: ace-gate
          token-header: header
          secret: 123456
#          服务鉴权种子（只配置在鉴权服务器）
          rsa-secret: xx1WET12^%3^(WE45
#       用户鉴权
        user:
          token-header: header
#          用户鉴权种子（只配置在鉴权服务器）
          rsa-secret: xx1WET12^%3^(WE45


